### ISSUE TITLE
pkgdown warning

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/iotables#12]
I think that this will relate to all packages. Any experience on this?  

When I generate an .md file from .Rmd, this is easy, just specify the new Github Flavored Markdown:

```
---
output:
  md_document:
    variant: gfm
---

```
However, with pre-existing md files (that follow the old Github definition) I do not know to make the conversion, and did not find any useful hints, apart from the fact that somebody wrote in Python a program that checks for differences?  It is not bothering me to much, but if you know a good solution, I'd use it in all packages. 

[WARNING] Deprecated: markdown_github. Use gfm instead.

**Comment by pitkant** [comment]
This is related to an issue with pandoc that is fixed in the development version of pkgdown but has not yet been implemented in the stable release. The warning should go away if you install the development version from GitHub:

`devtools::install_github("r-lib/pkgdown")`

**Comment by antaldaniel** [comment]
Thank you
