### ISSUE TITLE
Minor release 0.4.4

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/iotables#13]
I sent the current version with @KKulma and @pitkant added as contributors to CRAN, because for the preselection of the competition we need immediate news, and this will speed up communicating plans and expectations.  

I'd like to blog about the existance of the package, and planned enhancements.  I hope that these enhancements will be sent in a new, major release as 0.5 to CRAN in 2-3 weeks, with further blogposts on environmental impact analysis. 

As all checks seem to work without a hiss, I sent in to CRAN 0.4.4

**Comment by pitkant** [comment]
Great! A new release in CRAN might be possible in 2-3 weeks but generally speaking publishing new package versions that often is advised against in CRAN Repository Policy:

"Submitting updates should be done responsibly and with respect for the volunteers’ time. Once a package is established (which may take several rounds), “no more than every 1–2 months” seems appropriate."

**Comment by antaldaniel** [comment]
Well, I don't think that this is a very mature package, and the current 0.4.4. is just very overdue maintainance with the dependencies and recently introduced CRAN policies. 

The first submission did not pass, there are no \donttest{} rules, for example. 

But if you think you can pick up  the get_ghg issue and solve it, we can go for it now.

**Comment by pitkant** [comment]
I can help with sorting out CRAN checks if that helps, just post the check logs here. Adding \dontrun{} to tests that need an internet connection is a good idea anyway.

Implementing the new get_ghg() function falls too far away from my area of expertise for me to be comfortably able to evaluate whether it gives correct results or not.

**Comment by antaldaniel** [comment]
Here are the issues, they are very minor ones!
https://win-builder.r-project.org/incoming_pretest/iotables_0.4.4_20210601_140326/Windows/00check.log

**Comment by pitkant** [comment]
I have now made the most obvious fixes and pushed them to master. The package checks were OK on my machine and on check_win_devel

**Comment by KKulma** [comment]
@antaldaniel @pitkant all checks are passing now on `master`, is it now good for the CRAN release?

**Comment by antaldaniel** [comment]
@KKulma  My bad, that I did not close this, and you missed a few emails.  It is on CRAN. We even tried [to blog](https://greendeal.dataobservatory.eu/post/2021-06-03-iotables-release/) about it and get to Rbloggers.
