### ISSUE TITLE
Introductory blog post, first version

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/iotables#14]
We could also make some tutorials, if somebody has the time for it, but I think this could be something useful for Rbloggers, and as a start of an R Journal publication.

[Blogpost Draft: rOpenGov_intro.Rmd)](https://github.com/rOpenGov/iotables/blob/master/data-raw/rOpenGov_intro.Rmd)

**Comment by antagomir** [comment]
Ok with me - ideally Pyry could help to finalize at this point?

Just one comment on R-bloggers: the post should have substantial R content, i.e. not just explanations of plans. I am not sure if the present version fullfils this yet?

**Comment by antaldaniel** [comment]
@antagomir I agree with you, and the challenge with this package is that it deals with something very complex.  I think that I we can take out a few chunks from the [Working With Eurostat Data(https://iotables.dataobservatory.eu/articles/working_with_eurostat.html) as an example. 

I think you should think about how to present rOpenGov what else may be needed for such a blog post, and I can take out a managable size from that article.

**Comment by pitkant** [comment]
I did some proofreading and rearranged some sentences and paragraphs and pushed the changes in master but if they're not ok feel free to reject them. As for the subject matter, you are the expert.

Not every blog post has to be in R-bloggers (although exposure is of course good) and maybe this could be thought of as more of a less technical introduction to the subject of utility and uses of SIOT tables. Showcasing technical side of things could come later posts.

**Comment by antagomir** [comment]
Yes - thanks for both for discussion.

Pyry has a good point in that not all posts have to be in R-bloggers. The rOpenGov blog is independent but we can push selected posts to R-bloggers by tagging them.

If we use just rOpenGov but do not push to R-bloggers, then we have more freedom regarding contents, and we can have minimal, if any, R code in the post.

The first thing to decide is therefore whether we are willing to target R-bloggers specifically - or is rOpenGov blog sufficient? This will then influence how the post is to be finalized.

**Comment by antagomir** [comment]
Yes - thanks for both for discussion.

Pyry has a good point in that not all posts have to be in R-bloggers. The
rOpenGov blog is independent but we can push selected posts to R-bloggers
by tagging them.

If we use just rOpenGov but do not push to R-bloggers, then we have more
freedom regarding contents, and we can have minimal, if any, R code in the
post.

The first thing to decide is therefore whether we are willing to target
R-bloggers specifically - or is rOpenGov blog sufficient? This will then
influence how the post is to be finalized.

**Comment by antaldaniel** [comment]
Hi, 

I think that at this point, because of the Datathon, too, it would be very important to have more visibility on Rbloggers, but it would be also important to announce our collaboration in our ecosystem and in the rOpenGov community. 

We have a new release on CRAN. It is a good occassion.  We need some content on the pre-selection jurying on our webistes, so I'll post there first, and try to fine-tune the post in a way that it may fit both rOpenGov and Rbloggers.  But of course, we can take into pieces.  But generally, I think both for rOpenGov and for our Datathon entry being present on Rbloggers would be very good.

**Comment by pitkant** [comment]
Maybe R-Bloggers does not need to have that substantial R related content. According to their website:

> R-bloggers is R centric and therefor only accept posts which are directly related to R. That means that your posts (often) need to either have R code in them (or at least say the word “R”), or deal with the R system, R implementation of some interesting case study, or the R community. General (non R related) posts about statistics, programming or life do not belong here. If you blog about other things than R, that is fine, just make sure to create an “R” category in your blog and submit only it (if you don’t know what is your R category feed is, just submit it as is – and I will help you).

I think a post about an R package being published fulfils the above requirements with high marks. The blog post draft had some R code in it anyway.

**Comment by antagomir** [comment]
Should be all right to R-bloggers if it just includes some sensible R example with the new pkg.

**Comment by antaldaniel** [comment]
I uploaded one version (before proofreading, sorry, to have something there)  on all of our websites, see [here](https://economy.dataobservatory.eu/post/2021-06-03-iotables-release/) with code. In the data-raw/ folder you can find the blogpost in two versions, with and without code.  Please check it out and use / modify which you find best.  I uploaded in Rmd and md, and you can also use the hugo deployed ones from any hugo repo, they are all public.

**Comment by pitkant** [comment]
I did some minor fixes to the documents and pushed them to master. I think it's quite good now, maybe just some sort of conclusion / analysis after "select a few industries" part.

**Comment by antaldaniel** [comment]
Thank you @pitkant , I'll ask @ajgmolina to give it an outsider  read, and then I 'll upgate them on the observatory websites, and maybe you can put them to the rOpenGov blog, trying Rbloggers, as well?

**Comment by ajgmolina** [comment]
I just submitted a pull request.

**Comment by antaldaniel** [comment]
@ajgmolina thank you.  @antagomir , @pitkant , I think we have a blogpost then, right? (I'll change the edits in hugo tomorrow, please take care of the rOpengov/ Rbloggers version, but we'll speak tomorrow anyways.)

**Comment by pitkant** [comment]
I noticed that we didn't set any specific timeframe for our meeting today. It would probably be best to talk over the details in a short call. Starting at 14:30 EEST / 13:30 CEST / 12:30 WEST would suit @antagomir 's plans, would that be fine @antaldaniel ?

**Comment by antaldaniel** [comment]
Sorry, I just saw this, if you are still available, let's talk @antagomir @pitkant , send you an invite on email

**Comment by pitkant** [comment]
One final question before I put this to ropengov.org blog: What would you like the blog post title to be? "rOpenGov Intro" is not descriptive enough. I suggest "Economic and environmental impact analysis with iotables"

**Comment by antaldaniel** [comment]
@pitkant  Fully agree. 

This is our observatory version (with small summary/abstract on hugo). 
Economic and Environment Impact Analysis, Automated for Data-as-Service
rOpenGov, Reprex, and other open collaboration partners teamed up to build on our expertise of open source statistical software development further: we want to create a technologically and financially feasible data-as-service to put our reproducible research products into wider user for the business analyst, scientific researcher and evidence-based policy design communities. Our new release will help with automated economic impact and environmental impact analysis.
