### ISSUE TITLE
Create helper function and vignette for CO2 impact analysis

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/iotables#2]
- Most of this is already done, because the Croatia examples, and the employment effect are the same from an analytic point of view.

**Comment by KKulma** [comment]
@antaldaniel what exactly is still pending for this issue? If it's already done, I think we can close it if not, a list of expected additions would be very helpful, thanks!

**Comment by antaldaniel** [comment]
@KKulma  We started to create JORS, R Journal and maybe more applied publications from the pacakges, including this one.  This issue is ongoing, but reformulated in [#17](https://github.com/rOpenGov/iotables/issues/17). If you want to help co-authoring the papers, get in touch or follow the new issues, we are assigning them now after the 0.4.7 is released on CRAN.
