### ISSUE TITLE
Coding good practice, rlang, and dplyr 1.0+ for non-standard evaluation

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/iotables#3]
Most of this is done, and the rest are not necessarily practical, or easy to solve. 
There are some for loops that could be potentially changed to apply loops but not very straightforward how. 
If anyone sees anything that can be still made more efficient or clean, please give it a try.

Currently only very few left 

> checking Rd files ... WARNING
  checkRd: (5) iotables.Rd:0-106: Must have a \description

> checking R code for possible problems ... NOTE
  iotable_get: no visible binding for global variable '.data'
  Undefined global functions or variables:
    .data

0 errors √ | 1 warning x | 1 note x

**Comment by antaldaniel** [comment]
@KKulma @pitkant @antagomir , I made most changes, there are no warnings or notes, but if you run the goodpractices package on it, you see that the code could be improved, particularly with loops.  I use for loops, because I am bringing 64x64 matrxies to a perfect format, and with apply it would be far more difficult to debug.  

I may have left some dplyr 0.7 code, but other than that, the code is much improved since the last CRAN released and now passes all checks. If someobody wants to take a look and make minor edits, please go ahead, but on my part, this is release ready.

**Comment by antagomir** [comment]
Great, will have a look. 

I can see that there are contributor acknowledgements in README. I would suggest to do this through DESCRIPTION file as in [eurostat pkg](https://github.com/rOpenGov/eurostat/blob/master/DESCRIPTION) for instance?

**Comment by antaldaniel** [comment]
@antagomir , I wanted to ask everybody before release to give their credentials as contributors in DESCRIPTION but since you started it, I placed @pitkant and @KKulma on the contributor list (and gave a short thanks in NEWS). I'd like to keep the latest short thank you acknowledgements on the README last lines, because it also gets to the pkgdown front page. 

Huge thanks for @pitkant  the many-many small good practice implementations.
