### ISSUE TITLE
CI on github is failing

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/iotables#6]
I think that is is not a package error, some setting error on the running environment. 
On my local computer the package is building without errors, notes, and warnings. Though I have a hard time with the pkgdown, see [issue](https://github.com/rOpenGov/iotables/issues/5)

**Comment by KKulma** [comment]
this was fixed in #d0ddf35ed3065ec7cc38441e3f9d32d539794daa and can be closed now
